/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.sanpedro.systemcv.view;

import javax.swing.JButton;

/**
 *
 * @author Mysk
 */
public class FrmMainFarmacia extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainFarmacia
     */
    public FrmMainFarmacia() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public JButton getBtnInicio() {
        return jbtn_inicio;
    }

    public JButton getBtnMedicamentos() {
        return jbtn_medicamentos;
    }

    public JButton getBtnOrdenVenta() {
        return jbtn_ordenventa;
    }

    public JButton getBtnDespacharPedidos() {
        return jbtn_despacharpedidos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_VP = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbtn_inicio = new javax.swing.JButton();
        jbtn_despacharpedidos = new javax.swing.JButton();
        jbtn_medicamentos = new javax.swing.JButton();
        jbtn_ordenventa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pnl_VP.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_inicio.setText("Inicio");
        jbtn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        jbtn_despacharpedidos.setText("Despachar Pedidos");
        jPanel1.add(jbtn_despacharpedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 210, 50));

        jbtn_medicamentos.setText("Medicamentos");
        jPanel1.add(jbtn_medicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 210, 50));

        jbtn_ordenventa.setText("Orden de Venta");
        jPanel1.add(jbtn_ordenventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pnl_VP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pnl_VP, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_inicioActionPerformed

    }//GEN-LAST:event_jbtn_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Pnl_VP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_despacharpedidos;
    private javax.swing.JButton jbtn_inicio;
    private javax.swing.JButton jbtn_medicamentos;
    private javax.swing.JButton jbtn_ordenventa;
    // End of variables declaration//GEN-END:variables
}
